//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1269 with alias "assessoriaAtype"
	/// <summary>assessoriaAtype</summary>
	public partial interface IAssessoriaAtype : IPublishedContent
	{
		/// <summary>assessoriaAtype List</summary>
		Archetype.Models.ArchetypeModel AssessoriaAtypeList { get; }
	}

	/// <summary>assessoriaAtype</summary>
	[PublishedContentModel("assessoriaAtype")]
	public partial class AssessoriaAtype : PublishedContentModel, IAssessoriaAtype
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "assessoriaAtype";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AssessoriaAtype(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AssessoriaAtype, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// assessoriaAtype List
		///</summary>
		[ImplementPropertyType("assessoriaAtypeList")]
		public Archetype.Models.ArchetypeModel AssessoriaAtypeList
		{
			get { return GetAssessoriaAtypeList(this); }
		}

		/// <summary>Static getter for assessoriaAtype List</summary>
		public static Archetype.Models.ArchetypeModel GetAssessoriaAtypeList(IAssessoriaAtype that) { return that.GetPropertyValue<Archetype.Models.ArchetypeModel>("assessoriaAtypeList"); }
	}
}
