//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Clipping Item</summary>
	[PublishedContentModel("clippingItem")]
	public partial class ClippingItem : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "clippingItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ClippingItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ClippingItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Articles Date
		///</summary>
		[ImplementPropertyType("articleDateClip")]
		public DateTime ArticleDateClip
		{
			get { return this.GetPropertyValue<DateTime>("articleDateClip"); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("nameClip")]
		public string NameClip
		{
			get { return this.GetPropertyValue<string>("nameClip"); }
		}

		///<summary>
		/// News Body Text
		///</summary>
		[ImplementPropertyType("newsBodyTextClip")]
		public IHtmlString NewsBodyTextClip
		{
			get { return this.GetPropertyValue<IHtmlString>("newsBodyTextClip"); }
		}

		///<summary>
		/// News Image
		///</summary>
		[ImplementPropertyType("newsImageClip")]
		public IPublishedContent NewsImageClip
		{
			get { return this.GetPropertyValue<IPublishedContent>("newsImageClip"); }
		}

		///<summary>
		/// News Subtitle
		///</summary>
		[ImplementPropertyType("newsSubtitleClip")]
		public string NewsSubtitleClip
		{
			get { return this.GetPropertyValue<string>("newsSubtitleClip"); }
		}
	}
}
