//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1280 with alias "comunicacaoAtype"
	/// <summary>comunicacaoAtype</summary>
	public partial interface IComunicacaoAtype : IPublishedContent
	{
		/// <summary>Comunicação List</summary>
		Archetype.Models.ArchetypeModel ComunicacaoList { get; }
	}

	/// <summary>comunicacaoAtype</summary>
	[PublishedContentModel("comunicacaoAtype")]
	public partial class ComunicacaoAtype : PublishedContentModel, IComunicacaoAtype
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "comunicacaoAtype";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ComunicacaoAtype(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ComunicacaoAtype, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Comunicação List
		///</summary>
		[ImplementPropertyType("comunicacaoList")]
		public Archetype.Models.ArchetypeModel ComunicacaoList
		{
			get { return GetComunicacaoList(this); }
		}

		/// <summary>Static getter for Comunicação List</summary>
		public static Archetype.Models.ArchetypeModel GetComunicacaoList(IComunicacaoAtype that) { return that.GetPropertyValue<Archetype.Models.ArchetypeModel>("comunicacaoList"); }
	}
}
