//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1436 with alias "customDownloadTabs"
	/// <summary>customDownloadTabs</summary>
	public partial interface ICustomDownloadTabs : IPublishedContent
	{
		/// <summary>Download Picker</summary>
		Archetype.Models.ArchetypeModel DownloadPicker { get; }
	}

	/// <summary>customDownloadTabs</summary>
	[PublishedContentModel("customDownloadTabs")]
	public partial class CustomDownloadTabs : PublishedContentModel, ICustomDownloadTabs
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "customDownloadTabs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CustomDownloadTabs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CustomDownloadTabs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Download Picker
		///</summary>
		[ImplementPropertyType("downloadPicker")]
		public Archetype.Models.ArchetypeModel DownloadPicker
		{
			get { return GetDownloadPicker(this); }
		}

		/// <summary>Static getter for Download Picker</summary>
		public static Archetype.Models.ArchetypeModel GetDownloadPicker(ICustomDownloadTabs that) { return that.GetPropertyValue<Archetype.Models.ArchetypeModel>("downloadPicker"); }
	}
}
