//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1333 with alias "customTabs1"
	/// <summary>customTabsSlider</summary>
	public partial interface ICustomTabs1 : IPublishedContent
	{
		/// <summary>Tabs Slider</summary>
		Archetype.Models.ArchetypeModel TabsSlider { get; }
	}

	/// <summary>customTabsSlider</summary>
	[PublishedContentModel("customTabs1")]
	public partial class CustomTabs1 : PublishedContentModel, ICustomTabs1
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "customTabs1";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CustomTabs1(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CustomTabs1, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Tabs Slider
		///</summary>
		[ImplementPropertyType("tabsSlider")]
		public Archetype.Models.ArchetypeModel TabsSlider
		{
			get { return GetTabsSlider(this); }
		}

		/// <summary>Static getter for Tabs Slider</summary>
		public static Archetype.Models.ArchetypeModel GetTabsSlider(ICustomTabs1 that) { return that.GetPropertyValue<Archetype.Models.ArchetypeModel>("tabsSlider"); }
	}
}
