//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Fale com a Assessoria</summary>
	[PublishedContentModel("faleComAAssessoria")]
	public partial class FaleComAassessoria : Imprensa, IAssessoriaAtype, IComunicacaoAtype, IPageSubContentBlock
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "faleComAAssessoria";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FaleComAassessoria(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FaleComAassessoria, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// assessoriaAtype List
		///</summary>
		[ImplementPropertyType("assessoriaAtypeList")]
		public Archetype.Models.ArchetypeModel AssessoriaAtypeList
		{
			get { return Umbraco.Web.PublishedContentModels.AssessoriaAtype.GetAssessoriaAtypeList(this); }
		}

		///<summary>
		/// Comunicação List
		///</summary>
		[ImplementPropertyType("comunicacaoList")]
		public Archetype.Models.ArchetypeModel ComunicacaoList
		{
			get { return Umbraco.Web.PublishedContentModels.ComunicacaoAtype.GetComunicacaoList(this); }
		}

		///<summary>
		/// Page Body Text
		///</summary>
		[ImplementPropertyType("pageBodyText")]
		public IHtmlString PageBodyText
		{
			get { return Umbraco.Web.PublishedContentModels.PageSubContentBlock.GetPageBodyText(this); }
		}

		///<summary>
		/// Sub Title
		///</summary>
		[ImplementPropertyType("subTitle")]
		public string SubTitle
		{
			get { return Umbraco.Web.PublishedContentModels.PageSubContentBlock.GetSubTitle(this); }
		}

		///<summary>
		/// Sub Title Icon
		///</summary>
		[ImplementPropertyType("subTitleIcon")]
		public IPublishedContent SubTitleIcon
		{
			get { return Umbraco.Web.PublishedContentModels.PageSubContentBlock.GetSubTitleIcon(this); }
		}
	}
}
