//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1266 with alias "infoAtype"
	/// <summary>infoAtype</summary>
	public partial interface IInfoAtype : IPublishedContent
	{
		/// <summary>infoAtypeItem</summary>
		Archetype.Models.ArchetypeModel InfoAtypeItem { get; }
	}

	/// <summary>infoAtype</summary>
	[PublishedContentModel("infoAtype")]
	public partial class InfoAtype : PublishedContentModel, IInfoAtype
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "infoAtype";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public InfoAtype(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<InfoAtype, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// infoAtypeItem
		///</summary>
		[ImplementPropertyType("infoAtypeItem")]
		public Archetype.Models.ArchetypeModel InfoAtypeItem
		{
			get { return GetInfoAtypeItem(this); }
		}

		/// <summary>Static getter for infoAtypeItem</summary>
		public static Archetype.Models.ArchetypeModel GetInfoAtypeItem(IInfoAtype that) { return that.GetPropertyValue<Archetype.Models.ArchetypeModel>("infoAtypeItem"); }
	}
}
