//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Numeros Item</summary>
	[PublishedContentModel("numerosItem")]
	public partial class NumerosItem : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "numerosItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NumerosItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NumerosItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Numeros Data Block
		///</summary>
		[ImplementPropertyType("numerosDataBlock")]
		public string NumerosDataBlock
		{
			get { return this.GetPropertyValue<string>("numerosDataBlock"); }
		}

		///<summary>
		/// Numeros Description
		///</summary>
		[ImplementPropertyType("numerosDescription")]
		public IHtmlString NumerosDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("numerosDescription"); }
		}
	}
}
