//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Numeros Main</summary>
	[PublishedContentModel("numerosMain")]
	public partial class NumerosMain : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "numerosMain";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NumerosMain(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NumerosMain, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Numeros Data
		///</summary>
		[ImplementPropertyType("numerosData")]
		public string NumerosData
		{
			get { return this.GetPropertyValue<string>("numerosData"); }
		}

		///<summary>
		/// Numeros Text
		///</summary>
		[ImplementPropertyType("numerosText")]
		public IHtmlString NumerosText
		{
			get { return this.GetPropertyValue<IHtmlString>("numerosText"); }
		}
	}
}
