//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>rLinks</summary>
	[PublishedContentModel("rLinks")]
	public partial class RLinks : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "rLinks";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public RLinks(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<RLinks, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// anchorLinkOption
		///</summary>
		[ImplementPropertyType("anchorLinkOption")]
		public bool AnchorLinkOption
		{
			get { return this.GetPropertyValue<bool>("anchorLinkOption"); }
		}

		///<summary>
		/// r Links Target
		///</summary>
		[ImplementPropertyType("rLinksTarget")]
		public Umbraco.Web.Models.RelatedLinks RLinksTarget
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("rLinksTarget"); }
		}
	}
}
