//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1290 with alias "rLinks"
	/// <summary>rLinks</summary>
	public partial interface IRLinks : IPublishedContent
	{
		/// <summary>anchorLinkOption</summary>
		bool AnchorLinkOption { get; }

		/// <summary>r Links Target</summary>
		Umbraco.Web.Models.RelatedLinks RLinksTarget { get; }
	}

	/// <summary>rLinks</summary>
	[PublishedContentModel("rLinks")]
	public partial class RLinks : PublishedContentModel, IRLinks
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "rLinks";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public RLinks(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<RLinks, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// anchorLinkOption
		///</summary>
		[ImplementPropertyType("anchorLinkOption")]
		public bool AnchorLinkOption
		{
			get { return GetAnchorLinkOption(this); }
		}

		/// <summary>Static getter for anchorLinkOption</summary>
		public static bool GetAnchorLinkOption(IRLinks that) { return that.GetPropertyValue<bool>("anchorLinkOption"); }

		///<summary>
		/// r Links Target
		///</summary>
		[ImplementPropertyType("rLinksTarget")]
		public Umbraco.Web.Models.RelatedLinks RLinksTarget
		{
			get { return GetRLinksTarget(this); }
		}

		/// <summary>Static getter for r Links Target</summary>
		public static Umbraco.Web.Models.RelatedLinks GetRLinksTarget(IRLinks that) { return that.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("rLinksTarget"); }
	}
}
