//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1329 with alias "sliderPicturesComponent"
	/// <summary>Slider Pictures Component</summary>
	public partial interface ISliderPicturesComponent : IPublishedContent
	{
		/// <summary>Slider Pictures Picker</summary>
		IEnumerable<IPublishedContent> SliderPictures { get; }
	}

	/// <summary>Slider Pictures Component</summary>
	[PublishedContentModel("sliderPicturesComponent")]
	public partial class SliderPicturesComponent : PublishedContentModel, ISliderPicturesComponent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sliderPicturesComponent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SliderPicturesComponent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SliderPicturesComponent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Slider Pictures Picker
		///</summary>
		[ImplementPropertyType("sliderPictures")]
		public IEnumerable<IPublishedContent> SliderPictures
		{
			get { return GetSliderPictures(this); }
		}

		/// <summary>Static getter for Slider Pictures Picker</summary>
		public static IEnumerable<IPublishedContent> GetSliderPictures(ISliderPicturesComponent that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("sliderPictures"); }
	}
}
